// Fix: Added full content for constants.ts
import { Scenario } from './types';

export const SCENARIOS: Scenario[] = [
  // 일상
  {
    id: 'cafe-order',
    title: '카페에서 주문하기',
    emoji: '☕',
    description: '바리스타에게 좋아하는 커피를 주문하고 간단한 대화를 나눠보세요.',
    difficulty: '쉬움',
    category: '일상',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1559496417-e7f25cb247f3?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1463797221720-6b07e6426c24?w=800&auto=format&fit=crop&q=60',
    setting: 'You are at a local coffee shop.',
    userRole: '손님',
    aiRole: '바리스타',
    aiTutorName: 'Alex',
    task: 'Your goal is to order a drink, maybe ask for a recommendation, and make small talk with the barista.',
    initialMessage: "Hi there, what can I get for you today?",
    initialMessageReversed: "Hi, I'd like to order a coffee, please.",
    keyPhrases: [
      { phrase: "Can I get a...", meaning: "...주실 수 있나요?" },
      { phrase: "What do you recommend?", meaning: "추천해주실 만한 게 있나요?" },
      { phrase: "I'll have the same.", meaning: "저도 같은 걸로 할게요." },
      { phrase: "For here or to go?", meaning: "여기서 드시나요, 가져가시나요?" },
    ]
  },
  {
    id: 'grocery-shopping',
    title: '식료품점 쇼핑',
    emoji: '🛒',
    description: '가게 직원에게 원하는 물건이 어디 있는지 물어보고 계산을 하세요.',
    difficulty: '쉬움',
    category: '일상',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=60',
    setting: 'You are at a grocery store and can\'t find the pasta aisle.',
    userRole: '쇼핑객',
    aiRole: '가게 직원',
    aiTutorName: 'Ben',
    task: 'Ask a store employee where to find the pasta and then proceed to checkout.',
    initialMessage: "Excuse me, can I help you find something?",
    initialMessageReversed: "Excuse me, could you tell me where the pasta is?",
    keyPhrases: [
      { phrase: "Where can I find...?", meaning: "...은 어디에 있나요?" },
      { phrase: "Are you paying by cash or card?", meaning: "현금으로 하시겠어요, 카드로 하시겠어요?" },
      { phrase: "Do you need a bag?", meaning: "봉투 필요하세요?" },
      { phrase: "It's on aisle 5.", meaning: "5번 통로에 있습니다." },
    ]
  },
  {
    id: 'finding-directions',
    title: '길 물어보기',
    emoji: '🗺️',
    description: '낯선 도시에서 길을 잃었습니다. 현지인에게 길을 물어 목적지를 찾아가세요.',
    difficulty: '중간',
    category: '일상',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1528543606781-2f6e6857f318?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1549877452-9c387954fbc2?w=800&auto=format&fit=crop&q=60',
    setting: 'You are a tourist in New York City, looking for the nearest subway station.',
    userRole: '관광객',
    aiRole: '현지인',
    aiTutorName: 'Chloe',
    task: 'You need to ask a friendly-looking local for directions to the nearest subway station. Be polite and clear.',
    initialMessage: "Of course, I can help. Where are you trying to go?",
    initialMessageReversed: "Excuse me, I seem to be a bit lost. Can you help me?",
    keyPhrases: [
      { phrase: "How do I get to...?", meaning: "...에 어떻게 가나요?" },
      { phrase: "Is it far from here?", meaning: "여기서 먼가요?" },
      { phrase: "Could you show me on the map?", meaning: "지도에서 보여주실 수 있나요?" },
      { phrase: "Go straight ahead.", meaning: "직진하세요." },
    ]
  },
  {
    id: 'making-friends',
    title: '새로운 친구 사귀기',
    emoji: '👋',
    description: '파티에서 처음 만난 사람과 자연스럽게 대화를 시작하고 친해져 보세요.',
    difficulty: '중간',
    category: '일상',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&auto=format&fit=crop&q=60',
    setting: 'You are at a casual house party and you see someone you don\'t know.',
    userRole: '파티 참석자',
    aiRole: '처음 보는 사람',
    aiTutorName: 'Jamie',
    task: 'Start a conversation, find something in common, and try to make a new friend.',
    initialMessage: "Hey, I don't think we've met. I'm Alex. Great party, isn't it?",
    initialMessageReversed: "Hi! Yeah, it's a great party. I'm new here. What's your name?",
    keyPhrases: [
      { phrase: "So, what do you do for a living?", meaning: "무슨 일 하세요?" },
      { phrase: "How do you know the host?", meaning: "주최자랑은 어떻게 아는 사이세요?" },
      { phrase: "It was really nice meeting you.", meaning: "만나서 정말 반가웠어요." },
      { phrase: "Do you come here often?", meaning: "여기 자주 오세요?" },
    ]
  },
    {
    id: 'talk-weather',
    title: '날씨에 대해 이야기하기',
    emoji: '☀️',
    description: '이웃이나 동료와 날씨에 대해 가볍게 대화(스몰토크)하는 법을 연습합니다.',
    difficulty: '쉬움',
    category: '일상',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1510869882255-58be9fc697fa?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRvd258ZW58MHx8MHx8fDA%3D',
    setting: 'You run into your neighbor while checking the mail.',
    userRole: '나',
    aiRole: '이웃',
    aiTutorName: 'Mrs. Gable',
    task: 'Start a small talk conversation about the beautiful weather.',
    initialMessage: "Beautiful day, isn't it?",
    initialMessageReversed: "It sure is! I was just thinking of going for a walk.",
    keyPhrases: [
      { phrase: "It looks like it's going to rain.", meaning: "비가 올 것 같아요." },
      { phrase: "I can't believe how hot it is.", meaning: "이렇게 덥다니 믿을 수가 없네요." },
      { phrase: "I hope this weather lasts.", meaning: "이 날씨가 계속되면 좋겠어요." },
      { phrase: "Stay cool!", meaning: "시원하게 보내세요!" },
    ]
  },
  {
    id: 'making-reservation',
    title: '전화로 레스토랑 예약하기',
    emoji: '📞',
    description: '전화로 레스토랑에 저녁 식사를 예약하는 방법을 연습합니다.',
    difficulty: '중간',
    category: '일상',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=60',
    setting: 'You are calling a popular Italian restaurant to book a table for this Friday night.',
    userRole: '예약자',
    aiRole: '레스토랑 직원',
    aiTutorName: 'Maria',
    task: 'Call the restaurant and make a dinner reservation for two people for Friday at 7 PM.',
    initialMessage: "Good evening, \"Luigi's Italian Kitchen,\" how may I help you?",
    initialMessageReversed: "Hi, I'd like to make a reservation for this Friday.",
    keyPhrases: [
      { phrase: "I'd like to book a table for two.", meaning: "두 명 자리 예약하고 싶어요." },
      { phrase: "Do you have any availability for...?", meaning: "...에 가능한 시간 있나요?" },
      { phrase: "A table for two at 7 PM, please.", meaning: "오후 7시에 두 명 자리 부탁합니다." },
      { phrase: "Could I have your name, please?", meaning: "성함이 어떻게 되시나요?" },
    ]
  },
  {
    id: 'returning-item',
    title: '가게에 물건 환불하기',
    emoji: '🛍️',
    description: '최근에 구매한 상품에 문제가 있어 가게에 환불을 요청하는 상황입니다.',
    difficulty: '중간',
    category: '일상',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&auto=format&fit=crop&q=60',
    setting: 'You are at the customer service desk of a department store.',
    userRole: '손님',
    aiRole: '고객 서비스 직원',
    aiTutorName: 'David',
    task: 'Explain that the shirt you bought has a flaw and you would like to get a full refund.',
    initialMessage: "Hi, how can I help you today?",
    initialMessageReversed: "Hello, I'd like to return an item I purchased here yesterday.",
    keyPhrases: [
      { phrase: "I'd like to return this.", meaning: "이것을 반품하고 싶습니다." },
      { phrase: "It's faulty/damaged.", meaning: "결함이 있어요/손상되었어요." },
      { phrase: "Do you have the receipt?", meaning: "영수증 가지고 계신가요?" },
      { phrase: "I'd prefer a refund.", meaning: "환불을 받고 싶습니다." },
    ]
  },
  // 여행
  {
    id: 'hotel-check-in',
    title: '호텔 체크인',
    emoji: '🏨',
    description: '여행지에 도착하여 호텔에 체크인하는 상황을 연습합니다.',
    difficulty: '쉬움',
    category: '여행',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800',
    chatBackgroundImageUrl: 'https://plus.unsplash.com/premium_photo-1661929519129-7a76946c1d38?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aG90ZWx8ZW58MHx8MHx8fDA%3D',
    setting: 'You have just arrived at your hotel and are at the front desk to check in.',
    userRole: '호텔 투숙객',
    aiRole: '호텔 접수원',
    aiTutorName: 'Sarah',
    task: 'Check into your hotel room. You have a reservation under your name. You can also ask about hotel amenities.',
    initialMessage: "Welcome to our hotel! How can I help you today?",
    initialMessageReversed: "Hi, I'd like to check in. I have a reservation.",
    keyPhrases: [
      { phrase: "I have a reservation under the name...", meaning: "...이름으로 예약했습니다." },
      { phrase: "What time is checkout?", meaning: "체크아웃은 몇 시인가요?" },
      { phrase: "Could I get a wake-up call?", meaning: "모닝콜을 받을 수 있을까요?" },
      { phrase: "Enjoy your stay.", meaning: "편안한 시간 보내세요." },
    ]
  },
  {
    id: 'airport-security',
    title: '공항 보안 검색대',
    emoji: '✈️',
    description: '공항 보안 검색대를 통과하며 보안 요원과 대화하는 상황입니다.',
    difficulty: '중간',
    category: '여행',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=800&auto=format&fit=crop&q=60',
    setting: 'You are at the airport security checkpoint, about to go through the screening process.',
    userRole: '여행객',
    aiRole: '보안 요원',
    aiTutorName: 'Officer Miller',
    task: 'Follow the security agent\'s instructions to pass through the security check smoothly and quickly.',
    initialMessage: "Next, please. Place your bags on the belt and step forward.",
    initialMessageReversed: "Hi, do I need to take my shoes off?",
    keyPhrases: [
      { phrase: "Do I need to take my laptop out?", meaning: "노트북을 꺼내야 하나요?" },
      { phrase: "Please empty your pockets.", meaning: "주머니를 비워주세요." },
      { phrase: "Step through the scanner.", meaning: "스캐너를 통과하세요." },
      { phrase: "You're all set.", meaning: "다 되었습니다." },
    ]
  },
  {
    id: 'ordering-at-restaurant',
    title: '레스토랑에서 음식 주문',
    emoji: '🍽️',
    description: '웨이터와 소통하며 메뉴에 대해 질문하고 음식을 주문하는 연습을 합니다.',
    difficulty: '중간',
    category: '여행',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&auto=format&fit=crop&q=60',
    setting: 'You are seated at a nice restaurant, and the waiter has just come to your table.',
    userRole: '손님',
    aiRole: '웨이터',
    aiTutorName: 'Julian',
    task: 'Ask the waiter about the menu, order your meal, and ask for the bill when you are finished.',
    initialMessage: "Good evening! Are you ready to order, or would you like a few more minutes?",
    initialMessageReversed: "Excuse me, we're ready to order.",
    keyPhrases: [
      { phrase: "What's the special of the day?", meaning: "오늘의 특선 요리가 뭐예요?" },
      { phrase: "I'm allergic to nuts.", meaning: "저는 견과류 알레르기가 있어요." },
      { phrase: "Could we have the check, please?", meaning: "계산서 좀 주시겠어요?" },
      { phrase: "Everything was delicious, thank you.", meaning: "정말 맛있었어요, 감사합니다." },
    ]
  },
  {
    id: 'taking-a-taxi',
    title: '택시 타기',
    emoji: '🚕',
    description: '택시 기사에게 목적지를 말하고 요금을 지불하는 상황을 연습합니다.',
    difficulty: '쉬움',
    category: '여행',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1490650404312-a2175773bbf5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dGF4aXxlbnwwfHwwfHx8MA%3D%3D',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1600320254374-ce2d293c324e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    setting: 'You are hailing a taxi on a street corner in a foreign city.',
    userRole: '승객',
    aiRole: '택시 기사',
    aiTutorName: 'Mike',
    task: 'Tell the driver your destination, ask about the fare, and pay at the end of the ride.',
    initialMessage: "Where to?",
    initialMessageReversed: "Hi, could you take me to the Grand Palace Hotel?",
    keyPhrases: [
      { phrase: "Please take me to this address.", meaning: "이 주소로 가주세요." },
      { phrase: "How much will it cost?", meaning: "요금이 얼마나 나올까요?" },
      { phrase: "Keep the change.", meaning: "잔돈은 가지세요." },
      { phrase: "Could you drop me off here?", meaning: "여기서 내려주시겠어요?" },
    ]
  },
    {
    id: 'tourist-information',
    title: '관광 안내소 방문',
    emoji: 'ℹ️',
    description: '관광 안내소에서 도시 지도나 추천 장소에 대한 정보를 얻습니다.',
    difficulty: '중간',
    category: '여행',
    scenarioType: 'conversation',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661764174171-c29f85bd8a37?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8dG91cnxlbnwwfHwwfHx8MA%3D%3D',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1616036902568-fa623d8f0c0a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzh8fHRvdXJ8ZW58MHx8MHx8fDA%3D',
    setting: 'You are at the official city tourist information center.',
    userRole: '관광객',
    aiRole: '안내소 직원',
    aiTutorName: 'Emily',
    task: 'Ask for a city map and get recommendations for good local restaurants.',
    initialMessage: "Hello! Welcome to London. How can I assist you today?",
    initialMessageReversed: "Hi, could I get a map of the city, please?",
    keyPhrases: [
      { phrase: "What are the main attractions?", meaning: "주요 명소가 어디인가요?" },
      { phrase: "Can you recommend a good place to eat?", meaning: "괜찮은 식당을 추천해주실 수 있나요?" },
      { phrase: "Are there any walking tours?", meaning: "도보 관광 코스가 있나요?" },
      { phrase: "Thanks for your help.", meaning: "도와주셔서 감사합니다." },
    ]
  },
  {
    id: 'immigration-check',
    title: '공항 입국 심사',
    emoji: '🛂',
    description: '외국 공항에 도착하여 입국 심사관의 질문에 답하는 상황을 연습합니다.',
    difficulty: '중간',
    category: '여행',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGltbWlncmF0aW9ufGVufDB8fDB8fHww',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1517400508447-f8dd518b86db?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YWlycG9ydHxlbnwwfHwwfHx8MA%3D%3D',
    setting: 'You have just landed in the USA and are now at the immigration counter.',
    userRole: '방문객',
    aiRole: '입국 심사관',
    aiTutorName: 'Officer Davis',
    task: 'Answer the immigration officer\'s questions about the purpose of your visit and your length of stay.',
    initialMessage: "Good morning. Your passport, please.",
    initialMessageReversed: "Good morning. Here is my passport.",
    keyPhrases: [
      { phrase: "What's the purpose of your visit?", meaning: "방문 목적이 무엇인가요?" },
      { phrase: "I'm here for tourism/business.", meaning: "관광/사업차 왔습니다." },
      { phrase: "How long will you be staying?", meaning: "얼마나 머무를 예정인가요?" },
      { phrase: "Where will you be staying?", meaning: "어디서 묵을 건가요?" },
    ]
  },
  {
    id: 'renting-a-car',
    title: '자동차 렌트하기',
    emoji: '🚗',
    description: '렌터카 업체에서 여행에 필요한 차를 빌리는 과정을 연습합니다.',
    difficulty: '중간',
    category: '여행',
    scenarioType: 'conversation',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661290409901-c1408d58b661?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHJlbnRhbCUyMGNhcnxlbnwwfHwwfHx8MA%3D%3D',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1517524206127-48bbd363f3d7?w=800&auto=format&fit=crop&q=60',
    setting: 'You are at a car rental agency at the airport.',
    userRole: '고객',
    aiRole: '렌터카 직원',
    aiTutorName: 'Rachel',
    task: 'Rent a compact car for three days. Ask about insurance and the return policy.',
    initialMessage: "Hello, welcome to Swift Rentals. How can I help you today?",
    initialMessageReversed: "Hi, I have a reservation for a car.",
    keyPhrases: [
      { phrase: "I'd like to rent a car.", meaning: "차를 빌리고 싶어요." },
      { phrase: "What kind of car would you like?", meaning: "어떤 종류의 차를 원하시나요?" },
      { phrase: "Does it include insurance?", meaning: "보험이 포함되어 있나요?" },
      { phrase: "Where should I return the car?", meaning: "차는 어디에 반납해야 하나요?" },
    ]
  },
  // 비즈니스
  {
    id: 'job-interview',
    title: '면접 보기',
    emoji: '💼',
    description: '꿈의 직장을 위한 면접 상황입니다. 면접관의 질문에 자신있게 대답하세요.',
    difficulty: '어려움',
    category: '비즈니스',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1519074002996-a69e7ac46a42?w=800&auto=format&fit=crop&q=60',
    setting: 'You are in a job interview for a marketing manager position at a tech company.',
    userRole: '면접 지원자',
    aiRole: '채용 담당자',
    aiTutorName: 'Mr. Evans',
    task: 'Answer the interviewer\'s questions about your experience, skills, and why you want this job. You should also ask some thoughtful questions at the end.',
    initialMessage: "Thanks for coming in today. So, tell me a little bit about yourself.",
    initialMessageReversed: "Thank you for inviting me. I'm excited to be here.",
    keyPhrases: [
      { phrase: "What are your strengths and weaknesses?", meaning: "당신의 장점과 단점은 무엇인가요?" },
      { phrase: "Why are you interested in this position?", meaning: "왜 이 직책에 관심이 있나요?" },
      { phrase: "Where do you see yourself in five years?", meaning: "5년 후 자신의 모습은 어떨 것 같나요?" },
      { phrase: "Do you have any questions for me?", meaning: "저에게 질문 있으신가요?" },
    ]
  },
  {
    id: 'networking-event',
    title: '네트워킹 행사',
    emoji: '🤝',
    description: '업계 행사에서 새로운 사람들을 만나 가벼운 대화를 나누고 인맥을 쌓아보세요.',
    difficulty: '어려움',
    category: '비즈니스',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800&auto=format&fit=crop&q=60',
    setting: 'You are at a professional networking event for people in your industry.',
    userRole: '참석자',
    aiRole: '다른 참석자',
    aiTutorName: 'Daniel',
    task: 'Introduce yourself to someone new, explain what you do, and ask them about their work.',
    initialMessage: "Hi, this is a great event. My name is Alex. What brings you here?",
    initialMessageReversed: "Hi, I'm just trying to meet some new people. What do you do?",
    keyPhrases: [
      { phrase: "What field are you in?", meaning: "어떤 분야에 종사하세요?" },
      { phrase: "It was a pleasure talking to you.", meaning: "이야기 나눠서 즐거웠습니다." },
      { phrase: "Here's my card.", meaning: "제 명함입니다." },
      { phrase: "Let's keep in touch.", meaning: "계속 연락하고 지내요." },
    ]
  },
  {
    id: 'scheduling-meeting',
    title: '회의 일정 잡기',
    emoji: '📅',
    description: '동료와 함께 다음 주 회의를 위한 적절한 시간을 찾아 조율합니다.',
    difficulty: '중간',
    category: '비즈니스',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&auto=format&fit=crop&q=60',
    setting: 'You need to schedule a project sync-up meeting with a colleague for next week.',
    userRole: '나',
    aiRole: '동료',
    aiTutorName: 'Olivia',
    task: 'Find a time that works for both of you to have a 30-minute meeting next week.',
    initialMessage: "Hi, do you have a minute to schedule our project sync meeting?",
    initialMessageReversed: "Hey, sure. I was just about to message you about that. When are you free next week?",
    keyPhrases: [
      { phrase: "Does Tuesday afternoon work for you?", meaning: "화요일 오후 괜찮으세요?" },
      { phrase: "I'm afraid I'm busy then.", meaning: "죄송하지만 그때는 바빠요." },
      { phrase: "How about 3 PM on Wednesday?", meaning: "수요일 오후 3시는 어떠세요?" },
      { phrase: "Okay, I'll send you an invitation.", meaning: "좋아요, 제가 초대장을 보내드릴게요." },
    ]
  },
   {
    id: 'asking-for-help',
    title: '동료에게 도움 요청하기',
    emoji: '🙋',
    description: '업무 중 막히는 부분이 있어 동료에게 정중하게 도움을 요청하는 상황입니다.',
    difficulty: '중간',
    category: '비즈니스',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1516534775068-ba3e7458af70?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fG9mZmljZXxlbnwwfHwwfHx8MA%3D%3D',
    setting: 'You are stuck on a difficult task and need help from a more experienced colleague.',
    userRole: '나',
    aiRole: '선배 동료',
    aiTutorName: 'Chris',
    task: 'Politely interrupt your colleague and ask for their help with a problem.',
    initialMessage: "Sure, what's up? I have a few minutes.",
    initialMessageReversed: "Excuse me, Sarah? I know you're busy, but could I ask you a quick question?",
    keyPhrases: [
      { phrase: "I'm having some trouble with...", meaning: "...에 좀 어려움을 겪고 있어요." },
      { phrase: "Could you take a look at this?", meaning: "이것 좀 봐주실 수 있나요?" },
      { phrase: "I'd really appreciate your help.", meaning: "도와주시면 정말 감사하겠습니다." },
      { phrase: "That makes perfect sense.", meaning: "이제 완벽하게 이해가 되네요." },
    ]
  },
  {
    id: 'conference-call',
    title: '전화 회의 참여하기',
    emoji: '📞',
    description: '팀원들과 전화 회의를 하며 프로젝트 진행 상황에 대해 논의합니다.',
    difficulty: '어려움',
    category: '비즈니스',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1496171367470-9ed9a91ea931?w=800&auto=format&fit=crop&q=60',
    setting: 'You are on a conference call with your international team to discuss quarterly results.',
    userRole: '팀원',
    aiRole: '팀 리더',
    aiTutorName: 'John',
    task: 'Provide an update on your part of the project and ask clarifying questions about other team members\' progress.',
    initialMessage: "Okay everyone, thanks for joining. Let's start with a quick round of updates. John, can you kick us off?",
    initialMessageReversed: "Hi everyone, this is Sarah. Am I audible?",
    keyPhrases: [
      { phrase: "Can everyone hear me?", meaning: "다들 제 말 들리시나요?" },
      { phrase: "Sorry, you're breaking up a little.", meaning: "죄송한데, 목소리가 좀 끊겨요." },
      { phrase: "To piggyback on that...", meaning: "그 말에 덧붙이자면..." },
      { phrase: "Let's circle back to this later.", meaning: "이건 나중에 다시 논의하죠." },
    ]
  },
  {
    id: 'apologizing-for-mistake',
    title: '업무상 실수 사과하기',
    emoji: '🙇',
    description: '업무상 실수를 한 것에 대해 상사에게 사과하고 해결책을 제시합니다.',
    difficulty: '어려움',
    category: '비즈니스',
    scenarioType: 'conversation',
    imageUrl: 'https://images.unsplash.com/photo-1573497620053-ea5300f94f21?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHdvcmt8ZW58MHx8MHx8fDA%3D',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1606857521015-7f9fcf423740?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fG9mZmljZXxlbnwwfHwwfHx8MA%3D%3D',
    setting: 'You have made a mistake on an important report and need to inform your manager.',
    userRole: '직원',
    aiRole: '매니저',
    aiTutorName: 'Ms. Chen',
    task: 'Apologize for the mistake, explain how it happened, and present your plan to fix it.',
    initialMessage: "Do you have a moment? I need to talk to you about the Q3 report.",
    initialMessageReversed: "Excuse me, boss. I need to report a mistake I made on the Q3 report.",
    keyPhrases: [
      { phrase: "I'd like to apologize for...", meaning: "...에 대해 사과드립니다." },
      { phrase: "I take full responsibility.", meaning: "전적으로 제 책임입니다." },
      { phrase: "Here's how I plan to correct it.", meaning: "이렇게 해결할 계획입니다." },
      { phrase: "I'll make sure it won't happen again.", meaning: "다시는 이런 일이 없도록 하겠습니다." },
    ]
  },
  // 듣기
  {
    id: 'listening-mode',
    title: '듣기 집중 모드',
    emoji: '🎧',
    description: 'AI가 들려주는 짧은 이야기를 듣고, 내용에 대한 질문에 답해보세요.',
    difficulty: '중간',
    category: '듣기',
    scenarioType: 'listening',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800',
    chatBackgroundImageUrl: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&auto=format&fit=crop&q=60',
    setting: 'You are in a listening comprehension test. The AI will tell you a short story, and then ask you some questions about it.',
    userRole: '학생',
    aiRole: '내레이터',
    aiTutorName: 'Alex',
    task: 'Listen carefully to the story and answer the questions that follow to test your understanding.',
    initialMessage: "Hello! I'm going to tell you a short story about a man named Jack who found a lost puppy. Please listen carefully. Are you ready?",
    initialMessageReversed: "", // Not applicable for listening mode
    keyPhrases: [
      { phrase: "What was the main point?", meaning: "핵심 내용이 무엇이었나요?" },
      { phrase: "Could you repeat that?", meaning: "다시 한번 말씀해주시겠어요?" },
      { phrase: "I'm ready.", meaning: "준비됐어요." },
      { phrase: "That is correct.", meaning: "맞습니다." },
    ]
  },
];